// Calibration drill fact bank. Every answer here should be stable over time and well-sourced.
//
// Sourcing notes (checked September 2026):
// - Years, birth dates, heights, elevations, depths and diameters were checked against Wikipedia /
//   Wikidata, and the primary sources they cite where values looked surprising.
// - Planet diameters (equatorial) are from the NASA Planetary Fact Sheet; moon and dwarf-planet
//   diameters are mean diameters.
// - Country populations are World Bank (World Development Indicators) mid-2020 estimates, rounded to
//   0.1 million. Countries whose ordering flips between the World Bank and UN WPP editions were left out.
// - Country areas are total area (land + inland water) from Wikipedia's list (CIA World Factbook / UN
//   figures), rounded to the nearest 1,000 km². The US is omitted because its total area differs by
//   ~3% depending on whether coastal and territorial waters are counted.
// - Melting points are for the pure element at standard pressure (Wikipedia / CRC values).
// - City latitudes are the city coordinates used by Wikipedia.

export type FactKind = "year" | "number";
export type FactCategory = "History" | "Science" | "Geography" | "Space" | "Nature" | "Culture" | "Sports" | "Tech";

export const COMPARE_GROUPS = {
  "event-year": { prompt: "Which happened first?", higherWins: false },
  "birth-year": { prompt: "Who was born first?", higherWins: false },
  "structure-height": { prompt: "Which is taller?", higherWins: true },
  "mountain-height": { prompt: "Which peak is higher?", higherWins: true },
  "country-population": { prompt: "Which country had more people in 2020?", higherWins: true },
  "country-area": { prompt: "Which country is larger by total area?", higherWins: true },
  "body-diameter": { prompt: "Which has the larger diameter?", higherWins: true },
  "element-atomic-number": { prompt: "Which element has the higher atomic number?", higherWins: true },
  "melting-point": { prompt: "Which element has the higher melting point?", higherWins: true },
  "city-latitude": { prompt: "Which city is farther north?", higherWins: true },
  "lake-depth": { prompt: "Which lake is deeper at its deepest point?", higherWins: true },
} as const satisfies Record<string, { prompt: string; higherWins: boolean }>;
export type CompareGroup = keyof typeof COMPARE_GROUPS;

export interface Fact {
  id: string; // unique, stable kebab-case slug, e.g. "eiffel-tower-completed"
  q: string; // the interval question, e.g. "In what year was the Eiffel Tower completed?"
  label: string; // noun phrase used in comparisons, e.g. "the completion of the Eiffel Tower"
  answer: number; // the true value, in `unit`
  unit?: string; // shown after the number: "m", "km", "km²", "°C", "million people", "years", "km/h"... omit for years
  kind: FactKind; // "year" = calendar year (BC as negative, e.g. -44), formatted without thousands separators
  scale: "linear" | "log"; // "log" for positive quantities that span orders of magnitude or where error is naturally multiplicative (populations, distances, areas, masses, counts); "linear" for years, temperatures, and anything that can be ≤ 0
  cmp?: CompareGroup; // comparison group; two facts in the same group can be compared
  cat: FactCategory;
  note?: string; // optional one-line context shown after answering (≤ 120 chars); must itself be accurate
}

export const FACTS: Fact[] = [
  // ───────────────────────────── event-year ─────────────────────────────
  {
    id: "vesuvius-buries-pompeii",
    q: "In what year AD did Mount Vesuvius erupt and bury Pompeii?",
    label: "the eruption of Vesuvius that buried Pompeii",
    answer: 79,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "History",
    note: "The same eruption also buried the nearby town of Herculaneum.",
  },
  {
    id: "fall-of-western-roman-empire",
    q: "In what year was the last Western Roman emperor deposed, the traditional date for the fall of the Western Roman Empire?",
    label: "the fall of the Western Roman Empire",
    answer: 476,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "History",
    note: "Romulus Augustulus was deposed by Odoacer; the Eastern Roman Empire lasted until 1453.",
  },
  {
    id: "charlemagne-crowned-emperor",
    q: "In what year was Charlemagne crowned emperor by Pope Leo III?",
    label: "the coronation of Charlemagne as emperor",
    answer: 800,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "History",
    note: "He was crowned in Rome on Christmas Day.",
  },
  {
    id: "battle-of-hastings",
    q: "In what year was the Battle of Hastings fought?",
    label: "the Battle of Hastings",
    answer: 1066,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "History",
    note: "William of Normandy defeated King Harold II, beginning the Norman conquest of England.",
  },
  {
    id: "magna-carta-sealed",
    q: "In what year did King John of England agree to the Magna Carta?",
    label: "the sealing of the Magna Carta",
    answer: 1215,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "History",
    note: "Agreed at Runnymede, beside the River Thames.",
  },
  {
    id: "fall-of-constantinople",
    q: "In what year did Constantinople fall to the Ottoman Turks?",
    label: "the fall of Constantinople to the Ottomans",
    answer: 1453,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "History",
    note: "Its fall ended the Byzantine Empire.",
  },
  {
    id: "columbus-reaches-americas",
    q: "In what year did Christopher Columbus first reach the Americas?",
    label: "Columbus's first landfall in the Americas",
    answer: 1492,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "History",
    note: "He made landfall in the Bahamas in October 1492.",
  },
  {
    id: "luther-ninety-five-theses",
    q: "In what year did Martin Luther publish his Ninety-five Theses?",
    label: "Martin Luther's Ninety-five Theses",
    answer: 1517,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "History",
    note: "Traditionally dated 31 October 1517, the start of the Protestant Reformation.",
  },
  {
    id: "us-declaration-of-independence",
    q: "In what year was the US Declaration of Independence adopted?",
    label: "the US Declaration of Independence",
    answer: 1776,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "History",
    note: "Adopted by the Second Continental Congress on 4 July 1776.",
  },
  {
    id: "storming-of-the-bastille",
    q: "In what year was the Bastille stormed, at the start of the French Revolution?",
    label: "the storming of the Bastille",
    answer: 1789,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "History",
    note: "14 July is now France's national day.",
  },
  {
    id: "battle-of-waterloo",
    q: "In what year was the Battle of Waterloo fought?",
    label: "the Battle of Waterloo",
    answer: 1815,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "History",
    note: "Napoleon's final defeat, fought near Brussels.",
  },
  {
    id: "titanic-sinks",
    q: "In what year did the Titanic sink?",
    label: "the sinking of the Titanic",
    answer: 1912,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "History",
    note: "It sank on its maiden voyage in April 1912.",
  },
  {
    id: "indian-independence",
    q: "In what year did India gain independence from Britain?",
    label: "Indian independence from Britain",
    answer: 1947,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "History",
    note: "15 August 1947, accompanied by the partition that created Pakistan.",
  },
  {
    id: "chernobyl-disaster",
    q: "In what year did the Chernobyl nuclear disaster happen?",
    label: "the Chernobyl nuclear disaster",
    answer: 1986,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "History",
    note: "Reactor 4 exploded on 26 April 1986, in what was then the Soviet Union.",
  },
  {
    id: "fall-of-berlin-wall",
    q: "In what year did the Berlin Wall fall?",
    label: "the fall of the Berlin Wall",
    answer: 1989,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "History",
    note: "9 November 1989; Germany reunified the following year.",
  },
  {
    id: "copernicus-de-revolutionibus",
    q: "In what year did Copernicus publish De revolutionibus, his Sun-centred model of the solar system?",
    label: "the publication of Copernicus's Sun-centred model",
    answer: 1543,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "Science",
    note: "It was published in the year of his death.",
  },
  {
    id: "newton-principia-published",
    q: "In what year was Isaac Newton's Principia first published?",
    label: "the publication of Newton's Principia",
    answer: 1687,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "Science",
    note: "It set out his laws of motion and universal gravitation.",
  },
  {
    id: "jenner-smallpox-vaccine",
    q: "In what year did Edward Jenner carry out his first smallpox vaccination?",
    label: "Edward Jenner's first smallpox vaccination",
    answer: 1796,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "Science",
    note: "He used cowpox to protect 8-year-old James Phipps.",
  },
  {
    id: "origin-of-species-published",
    q: "In what year was Charles Darwin's On the Origin of Species published?",
    label: "the publication of On the Origin of Species",
    answer: 1859,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "Science",
    note: "It went on sale in November 1859.",
  },
  {
    id: "x-rays-discovered",
    q: "In what year did Wilhelm Röntgen discover X-rays?",
    label: "Röntgen's discovery of X-rays",
    answer: 1895,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "Science",
    note: "Röntgen received the first Nobel Prize in Physics, in 1901.",
  },
  {
    id: "penicillin-discovered",
    q: "In what year did Alexander Fleming discover penicillin?",
    label: "Fleming's discovery of penicillin",
    answer: 1928,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "Science",
    note: "He noticed a mould killing the bacteria on one of his culture plates.",
  },
  {
    id: "dna-double-helix",
    q: "In what year did Watson and Crick publish the double-helix structure of DNA?",
    label: "the discovery of DNA's double-helix structure",
    answer: 1953,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "Science",
    note: "Their model drew on X-ray diffraction work by Rosalind Franklin and Maurice Wilkins.",
  },
  {
    id: "suez-canal-opens",
    q: "In what year did the Suez Canal open?",
    label: "the opening of the Suez Canal",
    answer: 1869,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "Tech",
    note: "It links the Mediterranean Sea with the Red Sea.",
  },
  {
    id: "bell-telephone-patent",
    q: "In what year was Alexander Graham Bell granted his telephone patent?",
    label: "Bell's telephone patent",
    answer: 1876,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "Tech",
    note: "US patent 174,465 was granted on 7 March 1876.",
  },
  {
    id: "eiffel-tower-completed",
    q: "In what year was the Eiffel Tower completed?",
    label: "the completion of the Eiffel Tower",
    answer: 1889,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "Tech",
    note: "It was built as the entrance arch to the 1889 World's Fair in Paris.",
  },
  {
    id: "wright-brothers-first-flight",
    q: "In what year did the Wright brothers make the first powered airplane flight?",
    label: "the Wright brothers' first powered flight",
    answer: 1903,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "Tech",
    note: "At Kitty Hawk, North Carolina; the first flight lasted 12 seconds.",
  },
  {
    id: "transistor-invented",
    q: "In what year was the transistor invented at Bell Labs?",
    label: "the invention of the transistor",
    answer: 1947,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "Tech",
    note: "Bardeen, Brattain and Shockley shared the 1956 Nobel Prize in Physics for it.",
  },
  {
    id: "first-network-email",
    q: "In what year did Ray Tomlinson send the first email between computers on the ARPANET?",
    label: "the first email sent over the ARPANET",
    answer: 1971,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "Tech",
    note: "Tomlinson chose the @ sign to separate the user's name from the host computer's.",
  },
  {
    id: "google-founded",
    q: "In what year was Google founded?",
    label: "the founding of Google",
    answer: 1998,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "Tech",
    note: "Larry Page and Sergey Brin incorporated it in September 1998.",
  },
  {
    id: "first-iphone-released",
    q: "In what year was the first iPhone released?",
    label: "the release of the first iPhone",
    answer: 2007,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "Tech",
    note: "Announced in January and released in June 2007.",
  },
  {
    id: "uranus-discovered",
    q: "In what year did William Herschel discover Uranus?",
    label: "the discovery of Uranus",
    answer: 1781,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "Space",
    note: "The first planet discovered with a telescope.",
  },
  {
    id: "neptune-discovered",
    q: "In what year was Neptune discovered?",
    label: "the discovery of Neptune",
    answer: 1846,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "Space",
    note: "It was found close to the position Urbain Le Verrier had predicted mathematically.",
  },
  {
    id: "sputnik-launched",
    q: "In what year did the Soviet Union launch Sputnik 1?",
    label: "the launch of Sputnik 1",
    answer: 1957,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "Space",
    note: "The first artificial satellite.",
  },
  {
    id: "first-human-in-space",
    q: "In what year did Yuri Gagarin become the first human in space?",
    label: "Yuri Gagarin's flight into space",
    answer: 1961,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "Space",
    note: "Vostok 1 made one orbit of Earth in about 108 minutes.",
  },
  {
    id: "apollo-11-moon-landing",
    q: "In what year did Apollo 11 land the first humans on the Moon?",
    label: "the Apollo 11 Moon landing",
    answer: 1969,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "Space",
    note: "Neil Armstrong and Buzz Aldrin landed on 20 July 1969.",
  },
  {
    id: "hubble-launched",
    q: "In what year was the Hubble Space Telescope launched?",
    label: "the launch of the Hubble Space Telescope",
    answer: 1990,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "Space",
    note: "It was carried into orbit by the Space Shuttle Discovery.",
  },
  {
    id: "first-exoplanet-sunlike-star",
    q: "In what year was the first planet orbiting a Sun-like star (51 Pegasi b) discovered?",
    label: "the discovery of the first planet orbiting a Sun-like star",
    answer: 1995,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "Space",
    note: "Its discoverers, Michel Mayor and Didier Queloz, shared the 2019 Nobel Prize in Physics.",
  },
  {
    id: "first-nobel-prizes",
    q: "In what year were the first Nobel Prizes awarded?",
    label: "the first Nobel Prizes",
    answer: 1901,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "Culture",
    note: "They were awarded on the fifth anniversary of Alfred Nobel's death.",
  },
  {
    id: "sydney-opera-house-opens",
    q: "In what year did the Sydney Opera House open?",
    label: "the opening of the Sydney Opera House",
    answer: 1973,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "Culture",
    note: "Queen Elizabeth II formally opened it in October 1973.",
  },
  {
    id: "first-wimbledon",
    q: "In what year were the first Wimbledon Championships held?",
    label: "the first Wimbledon Championships",
    answer: 1877,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "Sports",
    note: "Wimbledon is the oldest tennis tournament in the world.",
  },
  {
    id: "first-modern-olympics",
    q: "In what year were the first modern Olympic Games held?",
    label: "the first modern Olympic Games",
    answer: 1896,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "Sports",
    note: "They were held in Athens.",
  },
  {
    id: "first-fifa-world-cup",
    q: "In what year was the first FIFA World Cup held?",
    label: "the first FIFA World Cup",
    answer: 1930,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "Sports",
    note: "Uruguay hosted it and won.",
  },
  {
    id: "first-four-minute-mile",
    q: "In what year did Roger Bannister run the first mile in under four minutes?",
    label: "the first sub-four-minute mile",
    answer: 1954,
    kind: "year",
    scale: "linear",
    cmp: "event-year",
    cat: "Sports",
    note: "He ran 3:59.4 at Oxford on 6 May 1954.",
  },

  // ───────────────────────────── birth-year ─────────────────────────────
  {
    id: "copernicus-born",
    q: "In what year was Nicolaus Copernicus born?",
    label: "Nicolaus Copernicus",
    answer: 1473,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "Science",
    note: "He was born in Toruń, in the Kingdom of Poland.",
  },
  {
    id: "galileo-born",
    q: "In what year was Galileo Galilei born?",
    label: "Galileo Galilei",
    answer: 1564,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "Science",
    note: "Born in Pisa, the same year as William Shakespeare.",
  },
  {
    id: "isaac-newton-born",
    q: "In what year was Isaac Newton born (by the Julian calendar then used in England)?",
    label: "Isaac Newton",
    answer: 1642,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "Science",
    note: "Christmas Day 1642 in the Julian calendar, which is 4 January 1643 in the Gregorian calendar.",
  },
  {
    id: "charles-darwin-born",
    q: "In what year was Charles Darwin born?",
    label: "Charles Darwin",
    answer: 1809,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "Science",
    note: "He was born on the same day as Abraham Lincoln: 12 February 1809.",
  },
  {
    id: "dmitri-mendeleev-born",
    q: "In what year was Dmitri Mendeleev, creator of the periodic table, born?",
    label: "Dmitri Mendeleev",
    answer: 1834,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "Science",
    note: "He published his periodic table in 1869.",
  },
  {
    id: "marie-curie-born",
    q: "In what year was Marie Curie born?",
    label: "Marie Curie",
    answer: 1867,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "Science",
    note: "Born in Warsaw; she is the only person to win Nobel Prizes in two different sciences.",
  },
  {
    id: "albert-einstein-born",
    q: "In what year was Albert Einstein born?",
    label: "Albert Einstein",
    answer: 1879,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "Science",
    note: "Born in Ulm, Germany, on 14 March, now celebrated as Pi Day.",
  },
  {
    id: "richard-feynman-born",
    q: "In what year was the physicist Richard Feynman born?",
    label: "Richard Feynman",
    answer: 1918,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "Science",
    note: "Born in New York City; he shared the 1965 Nobel Prize in Physics.",
  },
  {
    id: "stephen-hawking-born",
    q: "In what year was Stephen Hawking born?",
    label: "Stephen Hawking",
    answer: 1942,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "Science",
    note: "Born on 8 January 1942, exactly 300 years after Galileo died.",
  },
  {
    id: "ada-lovelace-born",
    q: "In what year was Ada Lovelace born?",
    label: "Ada Lovelace",
    answer: 1815,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "Tech",
    note: "She was the daughter of the poet Lord Byron.",
  },
  {
    id: "thomas-edison-born",
    q: "In what year was Thomas Edison born?",
    label: "Thomas Edison",
    answer: 1847,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "Tech",
    note: "Born the same year as Alexander Graham Bell.",
  },
  {
    id: "nikola-tesla-born",
    q: "In what year was Nikola Tesla born?",
    label: "Nikola Tesla",
    answer: 1856,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "Tech",
    note: "Born in the Austrian Empire, in what is now Croatia.",
  },
  {
    id: "alan-turing-born",
    q: "In what year was Alan Turing born?",
    label: "Alan Turing",
    answer: 1912,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "Tech",
    note: "Born in London; he died in 1954.",
  },
  {
    id: "steve-jobs-born",
    q: "In what year was Steve Jobs born?",
    label: "Steve Jobs",
    answer: 1955,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "Tech",
    note: "Born the same year as Bill Gates and Tim Berners-Lee.",
  },
  {
    id: "leonardo-da-vinci-born",
    q: "In what year was Leonardo da Vinci born?",
    label: "Leonardo da Vinci",
    answer: 1452,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "Culture",
    note: "Born near the town of Vinci, in the Republic of Florence.",
  },
  {
    id: "michelangelo-born",
    q: "In what year was Michelangelo born?",
    label: "Michelangelo",
    answer: 1475,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "Culture",
    note: "He was 23 years younger than Leonardo da Vinci.",
  },
  {
    id: "william-shakespeare-born",
    q: "In what year was William Shakespeare born?",
    label: "William Shakespeare",
    answer: 1564,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "Culture",
    note: "He was baptised on 26 April 1564 in Stratford-upon-Avon.",
  },
  {
    id: "js-bach-born",
    q: "In what year was Johann Sebastian Bach born?",
    label: "Johann Sebastian Bach",
    answer: 1685,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "Culture",
    note: "Born the same year as George Frideric Handel.",
  },
  {
    id: "mozart-born",
    q: "In what year was Wolfgang Amadeus Mozart born?",
    label: "Wolfgang Amadeus Mozart",
    answer: 1756,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "Culture",
    note: "Born in Salzburg; he died in 1791, aged 35.",
  },
  {
    id: "beethoven-born",
    q: "In what year was Ludwig van Beethoven born?",
    label: "Ludwig van Beethoven",
    answer: 1770,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "Culture",
    note: "He was baptised in Bonn on 17 December 1770.",
  },
  {
    id: "jane-austen-born",
    q: "In what year was Jane Austen born?",
    label: "Jane Austen",
    answer: 1775,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "Culture",
    note: "Pride and Prejudice was published in 1813.",
  },
  {
    id: "charles-dickens-born",
    q: "In what year was Charles Dickens born?",
    label: "Charles Dickens",
    answer: 1812,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "Culture",
    note: "He was born in Portsmouth, England.",
  },
  {
    id: "vincent-van-gogh-born",
    q: "In what year was Vincent van Gogh born?",
    label: "Vincent van Gogh",
    answer: 1853,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "Culture",
    note: "He died in 1890, aged 37.",
  },
  {
    id: "pablo-picasso-born",
    q: "In what year was Pablo Picasso born?",
    label: "Pablo Picasso",
    answer: 1881,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "Culture",
    note: "He was born in Málaga, Spain.",
  },
  {
    id: "frida-kahlo-born",
    q: "In what year was Frida Kahlo born?",
    label: "Frida Kahlo",
    answer: 1907,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "Culture",
    note: "She later claimed 1910, the year the Mexican Revolution began, as her birth year.",
  },
  {
    id: "elizabeth-i-born",
    q: "In what year was Queen Elizabeth I of England born?",
    label: "Elizabeth I of England",
    answer: 1533,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "History",
    note: "She was the daughter of Henry VIII and Anne Boleyn.",
  },
  {
    id: "george-washington-born",
    q: "In what year was George Washington born?",
    label: "George Washington",
    answer: 1732,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "History",
    note: "22 February 1732 (Gregorian); under the Julian calendar then in use it was 11 February 1731.",
  },
  {
    id: "napoleon-born",
    q: "In what year was Napoleon Bonaparte born?",
    label: "Napoleon Bonaparte",
    answer: 1769,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "History",
    note: "Born in Corsica, a year after Genoa ceded the island to France.",
  },
  {
    id: "abraham-lincoln-born",
    q: "In what year was Abraham Lincoln born?",
    label: "Abraham Lincoln",
    answer: 1809,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "History",
    note: "Born in Kentucky on the same day as Charles Darwin.",
  },
  {
    id: "queen-victoria-born",
    q: "In what year was Queen Victoria born?",
    label: "Queen Victoria",
    answer: 1819,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "History",
    note: "She became queen at 18, in 1837.",
  },
  {
    id: "mahatma-gandhi-born",
    q: "In what year was Mahatma Gandhi born?",
    label: "Mahatma Gandhi",
    answer: 1869,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "History",
    note: "His birthday, 2 October, is marked as the International Day of Non-Violence.",
  },
  {
    id: "winston-churchill-born",
    q: "In what year was Winston Churchill born?",
    label: "Winston Churchill",
    answer: 1874,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "History",
    note: "He was born at Blenheim Palace.",
  },
  {
    id: "nelson-mandela-born",
    q: "In what year was Nelson Mandela born?",
    label: "Nelson Mandela",
    answer: 1918,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "History",
    note: "He became South Africa's president in 1994.",
  },
  {
    id: "martin-luther-king-jr-born",
    q: "In what year was Martin Luther King Jr. born?",
    label: "Martin Luther King Jr.",
    answer: 1929,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "History",
    note: "Born in Atlanta; he was 34 when he gave his 'I Have a Dream' speech in 1963.",
  },
  {
    id: "pele-born",
    q: "In what year was the footballer Pelé born?",
    label: "Pelé",
    answer: 1940,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "Sports",
    note: "He won his first World Cup at 17, in 1958.",
  },
  {
    id: "muhammad-ali-born",
    q: "In what year was Muhammad Ali born?",
    label: "Muhammad Ali",
    answer: 1942,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "Sports",
    note: "He was born Cassius Clay in Louisville, Kentucky.",
  },
  {
    id: "neil-armstrong-born",
    q: "In what year was Neil Armstrong born?",
    label: "Neil Armstrong",
    answer: 1930,
    kind: "year",
    scale: "linear",
    cmp: "birth-year",
    cat: "Space",
    note: "He was 38 when he walked on the Moon.",
  },

  // ─────────────────────────── structure-height ───────────────────────────
  {
    id: "burj-khalifa-height",
    q: "How tall is the Burj Khalifa in Dubai, in metres?",
    label: "the Burj Khalifa",
    answer: 828,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "structure-height",
    cat: "Tech",
    note: "Opened in 2010; the very tip of its spire reaches 829.8 m.",
  },
  {
    id: "tokyo-skytree-height",
    q: "How tall is the Tokyo Skytree broadcasting tower, in metres?",
    label: "the Tokyo Skytree",
    answer: 634,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "structure-height",
    cat: "Tech",
    note: "6-3-4 can be read 'Mu-sa-shi', an old name for the region around Tokyo.",
  },
  {
    id: "cn-tower-height",
    q: "How tall is the CN Tower in Toronto, in metres?",
    label: "the CN Tower",
    answer: 553.3,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "structure-height",
    cat: "Tech",
    note: "Completed in 1976.",
  },
  {
    id: "one-world-trade-center-height",
    q: "How tall is One World Trade Center in New York, including its spire, in metres?",
    label: "One World Trade Center",
    answer: 541.3,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "structure-height",
    cat: "Tech",
    note: "1,776 feet, a nod to the year of American independence.",
  },
  {
    id: "petronas-towers-height",
    q: "How tall are the Petronas Towers in Kuala Lumpur, in metres?",
    label: "the Petronas Towers",
    answer: 452,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "structure-height",
    cat: "Tech",
    note: "Twin 88-storey towers linked by a skybridge.",
  },
  {
    id: "empire-state-building-height",
    q: "How tall is the Empire State Building to its roof, excluding the antenna, in metres?",
    label: "the Empire State Building",
    answer: 381,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "structure-height",
    cat: "Tech",
    note: "Completed in 1931; including its antenna it reaches about 443 m.",
  },
  {
    id: "gateway-arch-height",
    q: "How tall is the Gateway Arch in St. Louis, in metres?",
    label: "the Gateway Arch",
    answer: 192,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "structure-height",
    cat: "Culture",
    note: "It is exactly as wide at its base as it is tall: 630 feet.",
  },
  {
    id: "washington-monument-height",
    q: "How tall is the Washington Monument, in metres?",
    label: "the Washington Monument",
    answer: 169,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "structure-height",
    cat: "Culture",
    note: "The world's tallest structure from 1884 until the Eiffel Tower was completed in 1889.",
  },
  {
    id: "cologne-cathedral-height",
    q: "How tall are the twin spires of Cologne Cathedral, in metres?",
    label: "Cologne Cathedral",
    answer: 157,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "structure-height",
    cat: "Culture",
    note: "Construction began in 1248 and was not finished until 1880.",
  },
  {
    id: "great-pyramid-height",
    q: "How tall is the Great Pyramid of Giza today, in metres?",
    label: "the Great Pyramid of Giza",
    answer: 138.5,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "structure-height",
    cat: "Culture",
    note: "Originally about 146.6 m, before it lost its outer casing stones.",
  },
  {
    id: "elizabeth-tower-height",
    q: "How tall is the Elizabeth Tower, which houses London's Big Ben bell, in metres?",
    label: "Big Ben's clock tower (the Elizabeth Tower)",
    answer: 96,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "structure-height",
    cat: "Culture",
    note: "'Big Ben' is properly the nickname of the tower's great bell.",
  },
  {
    id: "statue-of-liberty-height",
    q: "How tall is the Statue of Liberty from the ground to the tip of the torch, including its pedestal, in metres?",
    label: "the Statue of Liberty (with its pedestal)",
    answer: 93,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "structure-height",
    cat: "Culture",
    note: "The copper statue itself is about 46 m tall.",
  },
  {
    id: "taj-mahal-height",
    q: "How tall is the Taj Mahal, in metres?",
    label: "the Taj Mahal",
    answer: 73,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "structure-height",
    cat: "Culture",
    note: "A mausoleum built by the Mughal emperor Shah Jahan for his wife Mumtaz Mahal.",
  },
  {
    id: "leaning-tower-of-pisa-height",
    q: "How tall is the Leaning Tower of Pisa, in metres?",
    label: "the Leaning Tower of Pisa",
    answer: 56,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "structure-height",
    cat: "Culture",
    note: "About 55.9 m on its low side and 56.7 m on its high side.",
  },
  {
    id: "christ-the-redeemer-height",
    q: "How tall is the Christ the Redeemer statue in Rio de Janeiro, excluding its pedestal, in metres?",
    label: "the Christ the Redeemer statue (without its pedestal)",
    answer: 30,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "structure-height",
    cat: "Culture",
    note: "Its pedestal adds 8 m; the outstretched arms span 28 m.",
  },

  // ─────────────────────────── mountain-height ───────────────────────────
  {
    id: "everest-elevation",
    q: "How high is the summit of Mount Everest above sea level, in metres?",
    label: "Mount Everest",
    answer: 8849,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "mountain-height",
    cat: "Nature",
    note: "Official height from the 2020 China–Nepal survey: 8,848.86 m.",
  },
  {
    id: "k2-elevation",
    q: "How high is the summit of K2 above sea level, in metres?",
    label: "K2",
    answer: 8611,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "mountain-height",
    cat: "Nature",
    note: "The second-highest mountain on Earth, on the China–Pakistan border.",
  },
  {
    id: "aconcagua-elevation",
    q: "How high is the summit of Aconcagua in Argentina above sea level, in metres?",
    label: "Aconcagua",
    answer: 6961,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "mountain-height",
    cat: "Nature",
    note: "The highest peak outside Asia; surveys differ by a few metres.",
  },
  {
    id: "denali-elevation",
    q: "How high is the summit of Denali (Mount McKinley) in Alaska above sea level, in metres?",
    label: "Denali (Mount McKinley)",
    answer: 6190,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "mountain-height",
    cat: "Nature",
    note: "North America's highest peak; remeasured in 2015 at 20,310 ft.",
  },
  {
    id: "kilimanjaro-elevation",
    q: "How high is the summit of Mount Kilimanjaro above sea level, in metres?",
    label: "Mount Kilimanjaro",
    answer: 5895,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "mountain-height",
    cat: "Nature",
    note: "Africa's highest peak; later GPS surveys differ from this official figure by a few metres.",
  },
  {
    id: "elbrus-elevation",
    q: "How high is the summit of Mount Elbrus above sea level, in metres?",
    label: "Mount Elbrus",
    answer: 5642,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "mountain-height",
    cat: "Nature",
    note: "A dormant volcano in the Caucasus, usually counted as Europe's highest peak.",
  },
  {
    id: "matterhorn-elevation",
    q: "How high is the summit of the Matterhorn above sea level, in metres?",
    label: "the Matterhorn",
    answer: 4478,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "mountain-height",
    cat: "Nature",
    note: "It stands on the border between Switzerland and Italy.",
  },
  {
    id: "mauna-kea-elevation",
    q: "How high is the summit of Mauna Kea in Hawaii above sea level, in metres?",
    label: "Mauna Kea",
    answer: 4207,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "mountain-height",
    cat: "Nature",
    note: "Measured from its underwater base, some authorities rank it the tallest mountain on Earth.",
  },
  {
    id: "mount-fuji-elevation",
    q: "How high is the summit of Mount Fuji above sea level, in metres?",
    label: "Mount Fuji",
    answer: 3776,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "mountain-height",
    cat: "Nature",
    note: "An active volcano; it last erupted in 1707.",
  },
  {
    id: "mount-olympus-elevation",
    q: "How high is the summit of Mount Olympus in Greece above sea level, in metres?",
    label: "Mount Olympus (Greece)",
    answer: 2918,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "mountain-height",
    cat: "Nature",
    note: "Greece's highest mountain, the mythical home of the gods.",
  },
  {
    id: "kosciuszko-elevation",
    q: "How high is the summit of Mount Kosciuszko above sea level, in metres?",
    label: "Mount Kosciuszko",
    answer: 2228,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "mountain-height",
    cat: "Nature",
    note: "The highest peak on mainland Australia.",
  },
  {
    id: "ben-nevis-elevation",
    q: "How high is the summit of Ben Nevis in Scotland above sea level, in metres?",
    label: "Ben Nevis",
    answer: 1345,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "mountain-height",
    cat: "Nature",
    note: "The highest mountain in the British Isles.",
  },

  // ────────────────── country-population (World Bank, mid-2020) ──────────────────
  {
    id: "china-population-2020",
    q: "What was the population of China in 2020, in millions?",
    label: "China",
    answer: 1411.1,
    unit: "million people",
    kind: "number",
    scale: "log",
    cmp: "country-population",
    cat: "Geography",
    note: "World Bank mid-2020 estimate. UN estimates say India overtook China in 2023.",
  },
  {
    id: "india-population-2020",
    q: "What was the population of India in 2020, in millions?",
    label: "India",
    answer: 1402.6,
    unit: "million people",
    kind: "number",
    scale: "log",
    cmp: "country-population",
    cat: "Geography",
    note: "World Bank mid-2020 estimate.",
  },
  {
    id: "usa-population-2020",
    q: "What was the population of the United States in 2020, in millions?",
    label: "the United States",
    answer: 331.6,
    unit: "million people",
    kind: "number",
    scale: "log",
    cmp: "country-population",
    cat: "Geography",
    note: "World Bank mid-2020 estimate; the April 2020 census counted 331.4 million.",
  },
  {
    id: "indonesia-population-2020",
    q: "What was the population of Indonesia in 2020, in millions?",
    label: "Indonesia",
    answer: 274.8,
    unit: "million people",
    kind: "number",
    scale: "log",
    cmp: "country-population",
    cat: "Geography",
    note: "World Bank mid-2020 estimate; the fourth most populous country.",
  },
  {
    id: "pakistan-population-2020",
    q: "What was the population of Pakistan in 2020, in millions?",
    label: "Pakistan",
    answer: 235.0,
    unit: "million people",
    kind: "number",
    scale: "log",
    cmp: "country-population",
    cat: "Geography",
    note: "World Bank mid-2020 estimate; the fifth most populous country.",
  },
  {
    id: "brazil-population-2020",
    q: "What was the population of Brazil in 2020, in millions?",
    label: "Brazil",
    answer: 208.7,
    unit: "million people",
    kind: "number",
    scale: "log",
    cmp: "country-population",
    cat: "Geography",
    note: "World Bank mid-2020 estimate.",
  },
  {
    id: "russia-population-2020",
    q: "What was the population of Russia in 2020, in millions?",
    label: "Russia",
    answer: 145.2,
    unit: "million people",
    kind: "number",
    scale: "log",
    cmp: "country-population",
    cat: "Geography",
    note: "World Bank mid-2020 estimate.",
  },
  {
    id: "japan-population-2020",
    q: "What was the population of Japan in 2020, in millions?",
    label: "Japan",
    answer: 126.3,
    unit: "million people",
    kind: "number",
    scale: "log",
    cmp: "country-population",
    cat: "Geography",
    note: "World Bank mid-2020 estimate; Japan's population has been shrinking since the late 2000s.",
  },
  {
    id: "germany-population-2020",
    q: "What was the population of Germany in 2020, in millions?",
    label: "Germany",
    answer: 83.2,
    unit: "million people",
    kind: "number",
    scale: "log",
    cmp: "country-population",
    cat: "Geography",
    note: "World Bank mid-2020 estimate; the most populous country in the EU.",
  },
  {
    id: "uk-population-2020",
    q: "What was the population of the United Kingdom in 2020, in millions?",
    label: "the United Kingdom",
    answer: 66.7,
    unit: "million people",
    kind: "number",
    scale: "log",
    cmp: "country-population",
    cat: "Geography",
    note: "World Bank mid-2020 estimate.",
  },
  {
    id: "canada-population-2020",
    q: "What was the population of Canada in 2020, in millions?",
    label: "Canada",
    answer: 38.0,
    unit: "million people",
    kind: "number",
    scale: "log",
    cmp: "country-population",
    cat: "Geography",
    note: "World Bank mid-2020 estimate.",
  },
  {
    id: "australia-population-2020",
    q: "What was the population of Australia in 2020, in millions?",
    label: "Australia",
    answer: 25.6,
    unit: "million people",
    kind: "number",
    scale: "log",
    cmp: "country-population",
    cat: "Geography",
    note: "World Bank mid-2020 estimate.",
  },

  // ───────────────────── country-area (total area, km²) ─────────────────────
  {
    id: "russia-area",
    q: "What is the total area of Russia (land plus inland water), in km²?",
    label: "Russia",
    answer: 17098000,
    unit: "km²",
    kind: "number",
    scale: "log",
    cmp: "country-area",
    cat: "Geography",
    note: "About 11% of Earth's land surface.",
  },
  {
    id: "canada-area",
    q: "What is the total area of Canada (land plus inland water), in km²?",
    label: "Canada",
    answer: 9985000,
    unit: "km²",
    kind: "number",
    scale: "log",
    cmp: "country-area",
    cat: "Geography",
    note: "The second-largest country; about 9% of its area is fresh water.",
  },
  {
    id: "china-area",
    q: "What is the total area of China (land plus inland water), in km²?",
    label: "China",
    answer: 9597000,
    unit: "km²",
    kind: "number",
    scale: "log",
    cmp: "country-area",
    cat: "Geography",
    note: "Excludes Taiwan and disputed territories; figures vary slightly by source.",
  },
  {
    id: "brazil-area",
    q: "What is the total area of Brazil (land plus inland water), in km²?",
    label: "Brazil",
    answer: 8510000,
    unit: "km²",
    kind: "number",
    scale: "log",
    cmp: "country-area",
    cat: "Geography",
    note: "Nearly half of South America.",
  },
  {
    id: "australia-area",
    q: "What is the total area of Australia (land plus inland water), in km²?",
    label: "Australia",
    answer: 7741000,
    unit: "km²",
    kind: "number",
    scale: "log",
    cmp: "country-area",
    cat: "Geography",
    note: "CIA World Factbook figure; Australia's own official land-area figure is slightly smaller.",
  },
  {
    id: "india-area",
    q: "What is the total area of India (land plus inland water), in km²?",
    label: "India",
    answer: 3287000,
    unit: "km²",
    kind: "number",
    scale: "log",
    cmp: "country-area",
    cat: "Geography",
    note: "Includes territory claimed by India but administered by Pakistan or China.",
  },
  {
    id: "argentina-area",
    q: "What is the total area of Argentina (land plus inland water), in km²?",
    label: "Argentina",
    answer: 2780000,
    unit: "km²",
    kind: "number",
    scale: "log",
    cmp: "country-area",
    cat: "Geography",
    note: "Excludes its claims in Antarctica and the Falkland Islands.",
  },
  {
    id: "mexico-area",
    q: "What is the total area of Mexico (land plus inland water), in km²?",
    label: "Mexico",
    answer: 1964000,
    unit: "km²",
    kind: "number",
    scale: "log",
    cmp: "country-area",
    cat: "Geography",
  },
  {
    id: "japan-area",
    q: "What is the total area of Japan (land plus inland water), in km²?",
    label: "Japan",
    answer: 378000,
    unit: "km²",
    kind: "number",
    scale: "log",
    cmp: "country-area",
    cat: "Geography",
    note: "Slightly larger than Germany.",
  },
  {
    id: "germany-area",
    q: "What is the total area of Germany (land plus inland water), in km²?",
    label: "Germany",
    answer: 358000,
    unit: "km²",
    kind: "number",
    scale: "log",
    cmp: "country-area",
    cat: "Geography",
  },
  {
    id: "uk-area",
    q: "What is the total area of the United Kingdom (land plus inland water), in km²?",
    label: "the United Kingdom",
    answer: 244000,
    unit: "km²",
    kind: "number",
    scale: "log",
    cmp: "country-area",
    cat: "Geography",
    note: "England, Scotland, Wales and Northern Ireland combined.",
  },

  // ─────────────────────────── body-diameter ───────────────────────────
  {
    id: "jupiter-diameter",
    q: "What is Jupiter's equatorial diameter, in km?",
    label: "Jupiter",
    answer: 142984,
    unit: "km",
    kind: "number",
    scale: "log",
    cmp: "body-diameter",
    cat: "Space",
    note: "About 11 times Earth's diameter.",
  },
  {
    id: "saturn-diameter",
    q: "What is Saturn's equatorial diameter, not counting its rings, in km?",
    label: "Saturn",
    answer: 120536,
    unit: "km",
    kind: "number",
    scale: "log",
    cmp: "body-diameter",
    cat: "Space",
    note: "Its average density is lower than that of water.",
  },
  {
    id: "uranus-diameter",
    q: "What is Uranus's equatorial diameter, in km?",
    label: "Uranus",
    answer: 51118,
    unit: "km",
    kind: "number",
    scale: "log",
    cmp: "body-diameter",
    cat: "Space",
    note: "Its axis is tilted about 98°, so it orbits the Sun on its side.",
  },
  {
    id: "neptune-diameter",
    q: "What is Neptune's equatorial diameter, in km?",
    label: "Neptune",
    answer: 49528,
    unit: "km",
    kind: "number",
    scale: "log",
    cmp: "body-diameter",
    cat: "Space",
    note: "Slightly smaller than Uranus, but more massive.",
  },
  {
    id: "earth-diameter",
    q: "What is Earth's equatorial diameter, in km?",
    label: "Earth",
    answer: 12756,
    unit: "km",
    kind: "number",
    scale: "log",
    cmp: "body-diameter",
    cat: "Space",
    note: "The pole-to-pole diameter is about 43 km shorter.",
  },
  {
    id: "venus-diameter",
    q: "What is Venus's equatorial diameter, in km?",
    label: "Venus",
    answer: 12104,
    unit: "km",
    kind: "number",
    scale: "log",
    cmp: "body-diameter",
    cat: "Space",
    note: "Only about 5% smaller than Earth.",
  },
  {
    id: "mars-diameter",
    q: "What is Mars's equatorial diameter, in km?",
    label: "Mars",
    answer: 6792,
    unit: "km",
    kind: "number",
    scale: "log",
    cmp: "body-diameter",
    cat: "Space",
    note: "Just over half of Earth's diameter.",
  },
  {
    id: "ganymede-diameter",
    q: "What is the diameter of Ganymede, Jupiter's largest moon, in km?",
    label: "Ganymede (Jupiter's largest moon)",
    answer: 5268,
    unit: "km",
    kind: "number",
    scale: "log",
    cmp: "body-diameter",
    cat: "Space",
    note: "The largest moon in the solar system, and bigger than the planet Mercury.",
  },
  {
    id: "titan-diameter",
    q: "What is the diameter of Titan, Saturn's largest moon, in km?",
    label: "Titan (Saturn's largest moon)",
    answer: 5150,
    unit: "km",
    kind: "number",
    scale: "log",
    cmp: "body-diameter",
    cat: "Space",
    note: "The only moon known to have a dense atmosphere.",
  },
  {
    id: "mercury-diameter",
    q: "What is the diameter of the planet Mercury, in km?",
    label: "Mercury",
    answer: 4879,
    unit: "km",
    kind: "number",
    scale: "log",
    cmp: "body-diameter",
    cat: "Space",
    note: "The smallest planet in the solar system.",
  },
  {
    id: "moon-diameter",
    q: "What is the diameter of the Moon, in km?",
    label: "the Moon",
    answer: 3475,
    unit: "km",
    kind: "number",
    scale: "log",
    cmp: "body-diameter",
    cat: "Space",
    note: "About 27% of Earth's diameter.",
  },
  {
    id: "pluto-diameter",
    q: "What is the diameter of Pluto, in km?",
    label: "Pluto",
    answer: 2376,
    unit: "km",
    kind: "number",
    scale: "log",
    cmp: "body-diameter",
    cat: "Space",
    note: "Measured precisely during NASA's New Horizons flyby in 2015.",
  },
  {
    id: "ceres-diameter",
    q: "What is the mean diameter of Ceres, the largest object in the asteroid belt, in km?",
    label: "Ceres (the largest object in the asteroid belt)",
    answer: 939,
    unit: "km",
    kind: "number",
    scale: "log",
    cmp: "body-diameter",
    cat: "Space",
    note: "Classified as a dwarf planet since 2006.",
  },

  // ─────────────────────── element-atomic-number ───────────────────────
  {
    id: "carbon-atomic-number",
    q: "What is the atomic number of carbon?",
    label: "carbon",
    answer: 6,
    kind: "number",
    scale: "log",
    cmp: "element-atomic-number",
    cat: "Science",
    note: "Carbon-14, used in radiocarbon dating, has 6 protons and 8 neutrons.",
  },
  {
    id: "oxygen-atomic-number",
    q: "What is the atomic number of oxygen?",
    label: "oxygen",
    answer: 8,
    kind: "number",
    scale: "log",
    cmp: "element-atomic-number",
    cat: "Science",
    note: "The most abundant element in Earth's crust by mass.",
  },
  {
    id: "sodium-atomic-number",
    q: "What is the atomic number of sodium?",
    label: "sodium",
    answer: 11,
    kind: "number",
    scale: "log",
    cmp: "element-atomic-number",
    cat: "Science",
    note: "Its symbol, Na, comes from the Latin natrium.",
  },
  {
    id: "calcium-atomic-number",
    q: "What is the atomic number of calcium?",
    label: "calcium",
    answer: 20,
    kind: "number",
    scale: "log",
    cmp: "element-atomic-number",
    cat: "Science",
    note: "The most abundant metal in the human body.",
  },
  {
    id: "iron-atomic-number",
    q: "What is the atomic number of iron?",
    label: "iron",
    answer: 26,
    kind: "number",
    scale: "log",
    cmp: "element-atomic-number",
    cat: "Science",
    note: "Its symbol, Fe, comes from the Latin ferrum.",
  },
  {
    id: "copper-atomic-number",
    q: "What is the atomic number of copper?",
    label: "copper",
    answer: 29,
    kind: "number",
    scale: "log",
    cmp: "element-atomic-number",
    cat: "Science",
    note: "Its symbol, Cu, comes from the Latin cuprum.",
  },
  {
    id: "silver-atomic-number",
    q: "What is the atomic number of silver?",
    label: "silver",
    answer: 47,
    kind: "number",
    scale: "log",
    cmp: "element-atomic-number",
    cat: "Science",
    note: "Its symbol, Ag, comes from the Latin argentum.",
  },
  {
    id: "tin-atomic-number",
    q: "What is the atomic number of tin?",
    label: "tin",
    answer: 50,
    kind: "number",
    scale: "log",
    cmp: "element-atomic-number",
    cat: "Science",
    note: "Its symbol, Sn, comes from the Latin stannum.",
  },
  {
    id: "gold-atomic-number",
    q: "What is the atomic number of gold?",
    label: "gold",
    answer: 79,
    kind: "number",
    scale: "log",
    cmp: "element-atomic-number",
    cat: "Science",
    note: "Its symbol, Au, comes from the Latin aurum.",
  },
  {
    id: "uranium-atomic-number",
    q: "What is the atomic number of uranium?",
    label: "uranium",
    answer: 92,
    kind: "number",
    scale: "log",
    cmp: "element-atomic-number",
    cat: "Science",
    note: "The heaviest element found in significant quantities in nature.",
  },

  // ─────────────────────────── melting-point ───────────────────────────
  {
    id: "nitrogen-melting-point",
    q: "What is the melting point of nitrogen, in °C?",
    label: "nitrogen",
    answer: -210,
    unit: "°C",
    kind: "number",
    scale: "linear",
    cmp: "melting-point",
    cat: "Science",
    note: "About 63 K; nitrogen is a gas at room temperature.",
  },
  {
    id: "mercury-melting-point",
    q: "What is the melting point of mercury, in °C?",
    label: "mercury",
    answer: -38.8,
    unit: "°C",
    kind: "number",
    scale: "linear",
    cmp: "melting-point",
    cat: "Science",
    note: "The only metal that is liquid at standard temperature and pressure.",
  },
  {
    id: "gallium-melting-point",
    q: "What is the melting point of gallium, in °C?",
    label: "gallium",
    answer: 29.8,
    unit: "°C",
    kind: "number",
    scale: "linear",
    cmp: "melting-point",
    cat: "Science",
    note: "Low enough that it can melt in your hand.",
  },
  {
    id: "tin-melting-point",
    q: "What is the melting point of tin, in °C?",
    label: "tin",
    answer: 231.9,
    unit: "°C",
    kind: "number",
    scale: "linear",
    cmp: "melting-point",
    cat: "Science",
    note: "Tin is a major ingredient of traditional solder.",
  },
  {
    id: "lead-melting-point",
    q: "What is the melting point of lead, in °C?",
    label: "lead",
    answer: 327.5,
    unit: "°C",
    kind: "number",
    scale: "linear",
    cmp: "melting-point",
    cat: "Science",
  },
  {
    id: "aluminium-melting-point",
    q: "What is the melting point of aluminium, in °C?",
    label: "aluminium",
    answer: 660.3,
    unit: "°C",
    kind: "number",
    scale: "linear",
    cmp: "melting-point",
    cat: "Science",
  },
  {
    id: "silver-melting-point",
    q: "What is the melting point of silver, in °C?",
    label: "silver",
    answer: 961.8,
    unit: "°C",
    kind: "number",
    scale: "linear",
    cmp: "melting-point",
    cat: "Science",
  },
  {
    id: "gold-melting-point",
    q: "What is the melting point of gold, in °C?",
    label: "gold",
    answer: 1064.2,
    unit: "°C",
    kind: "number",
    scale: "linear",
    cmp: "melting-point",
    cat: "Science",
    note: "Gold's freezing point is a defining fixed point of the International Temperature Scale.",
  },
  {
    id: "iron-melting-point",
    q: "What is the melting point of pure iron, in °C?",
    label: "iron",
    answer: 1538,
    unit: "°C",
    kind: "number",
    scale: "linear",
    cmp: "melting-point",
    cat: "Science",
    note: "Most steels melt at somewhat lower temperatures than pure iron.",
  },
  {
    id: "tungsten-melting-point",
    q: "What is the melting point of tungsten, in °C?",
    label: "tungsten",
    answer: 3422,
    unit: "°C",
    kind: "number",
    scale: "linear",
    cmp: "melting-point",
    cat: "Science",
    note: "The highest melting point of any metal.",
  },

  // ─────────────────────────── city-latitude ───────────────────────────
  {
    id: "reykjavik-latitude",
    q: "What is the latitude of central Reykjavík, in degrees north?",
    label: "Reykjavík",
    answer: 64.15,
    unit: "°N",
    kind: "number",
    scale: "linear",
    cmp: "city-latitude",
    cat: "Geography",
    note: "The northernmost capital of a sovereign state.",
  },
  {
    id: "london-latitude",
    q: "What is the latitude of central London, in degrees north?",
    label: "London",
    answer: 51.51,
    unit: "°N",
    kind: "number",
    scale: "linear",
    cmp: "city-latitude",
    cat: "Geography",
    note: "Farther north than any point in the contiguous United States.",
  },
  {
    id: "calgary-latitude",
    q: "What is the latitude of central Calgary, in degrees north?",
    label: "Calgary",
    answer: 51.05,
    unit: "°N",
    kind: "number",
    scale: "linear",
    cmp: "city-latitude",
    cat: "Geography",
    note: "Slightly south of London.",
  },
  {
    id: "vancouver-latitude",
    q: "What is the latitude of central Vancouver, in degrees north?",
    label: "Vancouver",
    answer: 49.26,
    unit: "°N",
    kind: "number",
    scale: "linear",
    cmp: "city-latitude",
    cat: "Geography",
    note: "Just north of the 49th parallel, which forms the western US–Canada border.",
  },
  {
    id: "paris-latitude",
    q: "What is the latitude of central Paris, in degrees north?",
    label: "Paris",
    answer: 48.86,
    unit: "°N",
    kind: "number",
    scale: "linear",
    cmp: "city-latitude",
    cat: "Geography",
    note: "Farther north than both Montreal and Quebec City.",
  },
  {
    id: "montreal-latitude",
    q: "What is the latitude of central Montreal, in degrees north?",
    label: "Montreal",
    answer: 45.51,
    unit: "°N",
    kind: "number",
    scale: "linear",
    cmp: "city-latitude",
    cat: "Geography",
    note: "At almost the same latitude as Venice and Milan.",
  },
  {
    id: "boston-latitude",
    q: "What is the latitude of central Boston, in degrees north?",
    label: "Boston",
    answer: 42.36,
    unit: "°N",
    kind: "number",
    scale: "linear",
    cmp: "city-latitude",
    cat: "Geography",
    note: "Slightly farther north than Rome.",
  },
  {
    id: "rome-latitude",
    q: "What is the latitude of central Rome, in degrees north?",
    label: "Rome",
    answer: 41.89,
    unit: "°N",
    kind: "number",
    scale: "linear",
    cmp: "city-latitude",
    cat: "Geography",
    note: "At almost the same latitude as Chicago.",
  },
  {
    id: "new-york-city-latitude",
    q: "What is the latitude of central New York City, in degrees north?",
    label: "New York City",
    answer: 40.71,
    unit: "°N",
    kind: "number",
    scale: "linear",
    cmp: "city-latitude",
    cat: "Geography",
    note: "Close to the latitudes of Naples and Madrid.",
  },
  {
    id: "beijing-latitude",
    q: "What is the latitude of central Beijing, in degrees north?",
    label: "Beijing",
    answer: 39.91,
    unit: "°N",
    kind: "number",
    scale: "linear",
    cmp: "city-latitude",
    cat: "Geography",
    note: "At almost the same latitude as Philadelphia.",
  },
  {
    id: "tokyo-latitude",
    q: "What is the latitude of central Tokyo, in degrees north?",
    label: "Tokyo",
    answer: 35.69,
    unit: "°N",
    kind: "number",
    scale: "linear",
    cmp: "city-latitude",
    cat: "Geography",
    note: "At almost the same latitude as Tehran.",
  },
  {
    id: "cairo-latitude",
    q: "What is the latitude of central Cairo, in degrees north?",
    label: "Cairo",
    answer: 30.04,
    unit: "°N",
    kind: "number",
    scale: "linear",
    cmp: "city-latitude",
    cat: "Geography",
    note: "Farther north than Houston and Miami.",
  },

  // ──────────────────────────── lake-depth ────────────────────────────
  {
    id: "lake-baikal-max-depth",
    q: "What is the maximum depth of Lake Baikal, in metres?",
    label: "Lake Baikal",
    answer: 1642,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "lake-depth",
    cat: "Nature",
    note: "The world's deepest lake, in Siberia.",
  },
  {
    id: "lake-tanganyika-max-depth",
    q: "What is the maximum depth of Lake Tanganyika, in metres?",
    label: "Lake Tanganyika",
    answer: 1470,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "lake-depth",
    cat: "Nature",
    note: "The world's second-deepest lake, shared by four African countries.",
  },
  {
    id: "caspian-sea-max-depth",
    q: "What is the maximum depth of the Caspian Sea, in metres?",
    label: "the Caspian Sea",
    answer: 1025,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "lake-depth",
    cat: "Nature",
    note: "Often counted as the world's largest lake by area.",
  },
  {
    id: "crater-lake-max-depth",
    q: "What is the maximum depth of Crater Lake in Oregon, in metres?",
    label: "Crater Lake (Oregon)",
    answer: 594,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "lake-depth",
    cat: "Nature",
    note: "The deepest lake in the United States, filling the caldera of a collapsed volcano.",
  },
  {
    id: "lake-tahoe-max-depth",
    q: "What is the maximum depth of Lake Tahoe, in metres?",
    label: "Lake Tahoe",
    answer: 501,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "lake-depth",
    cat: "Nature",
    note: "The second-deepest lake in the United States, after Crater Lake.",
  },
  {
    id: "lake-superior-max-depth",
    q: "What is the maximum depth of Lake Superior, in metres?",
    label: "Lake Superior",
    answer: 406,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "lake-depth",
    cat: "Nature",
    note: "The largest freshwater lake in the world by surface area.",
  },
  {
    id: "lake-geneva-max-depth",
    q: "What is the maximum depth of Lake Geneva, in metres?",
    label: "Lake Geneva",
    answer: 310,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "lake-depth",
    cat: "Nature",
    note: "It is shared by Switzerland and France.",
  },
  {
    id: "loch-ness-max-depth",
    q: "What is the maximum depth of Loch Ness, in metres?",
    label: "Loch Ness",
    answer: 230,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "lake-depth",
    cat: "Nature",
    note: "It holds more water than all the lakes in England and Wales combined.",
  },
  {
    id: "lake-victoria-max-depth",
    q: "What is the maximum depth of Lake Victoria, in metres?",
    label: "Lake Victoria",
    answer: 81,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "lake-depth",
    cat: "Nature",
    note: "Africa's largest lake by area, yet relatively shallow.",
  },
  {
    id: "lake-erie-max-depth",
    q: "What is the maximum depth of Lake Erie, in metres?",
    label: "Lake Erie",
    answer: 64,
    unit: "m",
    kind: "number",
    scale: "log",
    cmp: "lake-depth",
    cat: "Nature",
    note: "The shallowest of the five Great Lakes.",
  },

  // ─────────────────────────── interval-only ───────────────────────────
  // Science
  {
    id: "speed-of-light",
    q: "What is the speed of light in a vacuum, in km per second?",
    label: "the speed of light",
    answer: 299792.458,
    unit: "km/s",
    kind: "number",
    scale: "log",
    cat: "Science",
    note: "An exact value, fixed by the definition of the metre since 1983.",
  },
  {
    id: "speed-of-sound-air",
    q: "What is the speed of sound in dry air at 20 °C, in metres per second?",
    label: "the speed of sound in air",
    answer: 343,
    unit: "m/s",
    kind: "number",
    scale: "log",
    cat: "Science",
    note: "About 1,235 km/h.",
  },
  {
    id: "absolute-zero-celsius",
    q: "What is absolute zero, in °C?",
    label: "absolute zero",
    answer: -273.15,
    unit: "°C",
    kind: "number",
    scale: "linear",
    cat: "Science",
    note: "0 kelvin, the lowest possible temperature.",
  },
  {
    id: "adult-human-bones",
    q: "How many bones are in the typical adult human skeleton?",
    label: "the number of bones in the adult human body",
    answer: 206,
    unit: "bones",
    kind: "number",
    scale: "log",
    cat: "Science",
    note: "Newborns have around 270, many of which fuse together as they grow.",
  },
  {
    id: "human-chromosomes",
    q: "How many chromosomes are in a typical human body cell?",
    label: "the number of chromosomes in a human cell",
    answer: 46,
    unit: "chromosomes",
    kind: "number",
    scale: "log",
    cat: "Science",
    note: "23 pairs, one set inherited from each parent.",
  },
  // Space
  {
    id: "earth-moon-distance",
    q: "What is the average distance from Earth to the Moon, in km?",
    label: "the average Earth–Moon distance",
    answer: 384400,
    unit: "km",
    kind: "number",
    scale: "log",
    cat: "Space",
    note: "Roughly 30 Earth diameters.",
  },
  {
    id: "earth-sun-distance",
    q: "What is Earth's average distance from the Sun, in millions of km?",
    label: "the average Earth–Sun distance",
    answer: 149.6,
    unit: "million km",
    kind: "number",
    scale: "log",
    cat: "Space",
    note: "This distance defines the astronomical unit (AU).",
  },
  {
    id: "sun-diameter",
    q: "What is the diameter of the Sun, in km?",
    label: "the diameter of the Sun",
    answer: 1391400,
    unit: "km",
    kind: "number",
    scale: "log",
    cat: "Space",
    note: "About 109 times Earth's diameter.",
  },
  {
    id: "proxima-centauri-distance",
    q: "How far is Proxima Centauri, the nearest star to the Sun, in light-years?",
    label: "the distance to Proxima Centauri",
    answer: 4.25,
    unit: "light-years",
    kind: "number",
    scale: "log",
    cat: "Space",
    note: "The Gaia satellite measured 4.2465 light-years.",
  },
  {
    id: "apollo-moonwalkers",
    q: "How many people walked on the Moon during the Apollo program?",
    label: "the number of Apollo moonwalkers",
    answer: 12,
    unit: "people",
    kind: "number",
    scale: "log",
    cat: "Space",
    note: "Six crewed landings, from Apollo 11 in 1969 to Apollo 17 in 1972.",
  },
  // Nature
  {
    id: "octopus-hearts",
    q: "How many hearts does an octopus have?",
    label: "the number of hearts in an octopus",
    answer: 3,
    unit: "hearts",
    kind: "number",
    scale: "log",
    cat: "Nature",
    note: "One pumps blood around the body; two pump it through the gills.",
  },
  {
    id: "honeybee-eyes",
    q: "How many eyes does a honey bee have?",
    label: "the number of eyes on a honey bee",
    answer: 5,
    unit: "eyes",
    kind: "number",
    scale: "log",
    cat: "Nature",
    note: "Two large compound eyes plus three small simple eyes (ocelli) on top of the head.",
  },
  {
    id: "giraffe-neck-vertebrae",
    q: "How many vertebrae are in a giraffe's neck?",
    label: "the number of vertebrae in a giraffe's neck",
    answer: 7,
    unit: "vertebrae",
    kind: "number",
    scale: "log",
    cat: "Nature",
    note: "The same number as in a human neck; each one can be over 28 cm long.",
  },
  {
    id: "adult-dog-teeth",
    q: "How many teeth does an adult dog normally have?",
    label: "the number of teeth in an adult dog",
    answer: 42,
    unit: "teeth",
    kind: "number",
    scale: "log",
    cat: "Nature",
    note: "Ten more than an adult human's 32.",
  },
  {
    id: "african-elephant-gestation",
    q: "How long is an African elephant's pregnancy, in months?",
    label: "the gestation period of an African elephant",
    answer: 22,
    unit: "months",
    kind: "number",
    scale: "log",
    cat: "Nature",
    note: "The longest pregnancy of any land mammal.",
  },
  {
    id: "angel-falls-height",
    q: "How tall is Angel Falls in Venezuela, in metres?",
    label: "the height of Angel Falls",
    answer: 979,
    unit: "m",
    kind: "number",
    scale: "log",
    cat: "Nature",
    note: "The world's tallest uninterrupted waterfall; its longest single drop is 807 m.",
  },
  {
    id: "vostok-record-low",
    q: "What temperature was recorded at Antarctica's Vostok Station on 21 July 1983, the lowest ever measured by a weather station, in °C?",
    label: "the Vostok Station record low",
    answer: -89.2,
    unit: "°C",
    kind: "number",
    scale: "linear",
    cat: "Nature",
    note: "Satellites have since detected even colder snow-surface temperatures, around −98 °C.",
  },
  // Geography
  {
    id: "earth-circumference",
    q: "What is Earth's circumference at the equator, in km?",
    label: "Earth's equatorial circumference",
    answer: 40075,
    unit: "km",
    kind: "number",
    scale: "log",
    cat: "Geography",
    note: "The metre was originally defined as one ten-millionth of the distance from pole to equator.",
  },
  {
    id: "un-member-states-2020",
    q: "How many member states did the United Nations have in 2020?",
    label: "the number of UN member states",
    answer: 193,
    unit: "member states",
    kind: "number",
    scale: "log",
    cat: "Geography",
    note: "South Sudan, admitted in 2011, was the newest.",
  },
  // History
  {
    id: "hundred-years-war-duration",
    q: "How many years did the Hundred Years' War between England and France last?",
    label: "the length of the Hundred Years' War",
    answer: 116,
    unit: "years",
    kind: "number",
    scale: "log",
    cat: "History",
    note: "From 1337 to 1453, with long truces in between.",
  },
  {
    id: "louis-xiv-reign",
    q: "For how many years did Louis XIV reign as King of France?",
    label: "the length of Louis XIV's reign",
    answer: 72,
    unit: "years",
    kind: "number",
    scale: "log",
    cat: "History",
    note: "1643–1715: 72 years and 110 days. He became king at the age of four.",
  },
  {
    id: "elizabeth-ii-reign",
    q: "For how many years did Queen Elizabeth II reign?",
    label: "the length of Elizabeth II's reign",
    answer: 70,
    unit: "years",
    kind: "number",
    scale: "log",
    cat: "History",
    note: "1952–2022: 70 years and 214 days, the longest of any British monarch.",
  },
  {
    id: "declaration-signers",
    q: "How many delegates signed the US Declaration of Independence?",
    label: "the number of signers of the Declaration of Independence",
    answer: 56,
    unit: "signers",
    kind: "number",
    scale: "log",
    cat: "History",
    note: "Most of them signed on 2 August 1776, not on 4 July.",
  },
  {
    id: "berlin-wall-years-standing",
    q: "For how many years did the Berlin Wall stand?",
    label: "the number of years the Berlin Wall stood",
    answer: 28,
    unit: "years",
    kind: "number",
    scale: "log",
    cat: "History",
    note: "From August 1961 until November 1989.",
  },
  {
    id: "hadrians-wall-length",
    q: "How long was Hadrian's Wall across northern Britain, in km?",
    label: "the length of Hadrian's Wall",
    answer: 117,
    unit: "km",
    kind: "number",
    scale: "log",
    cat: "History",
    note: "80 Roman miles; construction began around AD 122.",
  },
  {
    id: "siege-of-leningrad-days",
    q: "How many days did the Siege of Leningrad last during World War II?",
    label: "the length of the Siege of Leningrad",
    answer: 872,
    unit: "days",
    kind: "number",
    scale: "log",
    cat: "History",
    note: "From September 1941 to January 1944.",
  },
  // Culture
  {
    id: "piano-keys",
    q: "How many keys does a standard modern piano have?",
    label: "the number of keys on a piano",
    answer: 88,
    unit: "keys",
    kind: "number",
    scale: "log",
    cat: "Culture",
    note: "52 white keys and 36 black keys.",
  },
  {
    id: "michelangelo-david-height",
    q: "How tall is Michelangelo's marble statue of David, in metres?",
    label: "the height of Michelangelo's David",
    answer: 5.17,
    unit: "m",
    kind: "number",
    scale: "log",
    cat: "Culture",
    note: "Carved from a single block of marble between 1501 and 1504.",
  },
  {
    id: "mona-lisa-height",
    q: "How tall is Leonardo da Vinci's Mona Lisa painting, in centimetres?",
    label: "the height of the Mona Lisa",
    answer: 77,
    unit: "cm",
    kind: "number",
    scale: "log",
    cat: "Culture",
    note: "It measures 77 × 53 cm and is painted in oil on a poplar panel.",
  },
  {
    id: "shakespeare-sonnets",
    q: "How many sonnets were in the 1609 collection of Shakespeare's sonnets?",
    label: "the number of Shakespeare's sonnets",
    answer: 154,
    unit: "sonnets",
    kind: "number",
    scale: "log",
    cat: "Culture",
    note: "Sonnet 18 begins 'Shall I compare thee to a summer's day?'",
  },
  {
    id: "titanic-film-oscars",
    q: "How many Academy Awards did James Cameron's 1997 film Titanic win?",
    label: "the number of Oscars won by Titanic (1997)",
    answer: 11,
    unit: "Oscars",
    kind: "number",
    scale: "log",
    cat: "Culture",
    note: "It won 11 of its 14 nominations, including Best Picture.",
  },
  {
    id: "bayeux-tapestry-length",
    q: "How long is the Bayeux Tapestry, in metres?",
    label: "the length of the Bayeux Tapestry",
    answer: 68.4,
    unit: "m",
    kind: "number",
    scale: "log",
    cat: "Culture",
    note: "It depicts the Norman Conquest; strictly speaking it is an embroidery, not a tapestry.",
  },
  // Sports
  {
    id: "marathon-distance",
    q: "How long is a marathon, in km?",
    label: "the marathon distance",
    answer: 42.195,
    unit: "km",
    kind: "number",
    scale: "log",
    cat: "Sports",
    note: "Standardised in 1921, based on the course of the 1908 London Olympic marathon.",
  },
  {
    id: "basketball-rim-height",
    q: "How high above the floor is a regulation basketball rim, in metres?",
    label: "the height of a basketball rim",
    answer: 3.05,
    unit: "m",
    kind: "number",
    scale: "log",
    cat: "Sports",
    note: "Exactly 10 feet.",
  },
  {
    id: "soccer-goal-width",
    q: "How wide is a regulation soccer (association football) goal, in metres?",
    label: "the width of a soccer goal",
    answer: 7.32,
    unit: "m",
    kind: "number",
    scale: "log",
    cat: "Sports",
    note: "8 yards wide and 8 feet (2.44 m) high.",
  },
  {
    id: "cricket-pitch-length",
    q: "How long is a cricket pitch from wicket to wicket, in metres?",
    label: "the length of a cricket pitch",
    answer: 20.12,
    unit: "m",
    kind: "number",
    scale: "log",
    cat: "Sports",
    note: "22 yards, the length of one chain.",
  },
  {
    id: "golf-hole-diameter",
    q: "What is the diameter of a golf hole, in millimetres?",
    label: "the diameter of a golf hole",
    answer: 108,
    unit: "mm",
    kind: "number",
    scale: "log",
    cat: "Sports",
    note: "4.25 inches.",
  },
  {
    id: "mens-shot-put-mass",
    q: "How much does the shot used in men's shot put weigh, in kg?",
    label: "the mass of a men's shot put",
    answer: 7.26,
    unit: "kg",
    kind: "number",
    scale: "log",
    cat: "Sports",
    note: "16 pounds; the women's shot weighs 4 kg.",
  },
  {
    id: "bolt-100m-world-record",
    q: "What time did Usain Bolt run when he set the 100 m world record at the 2009 World Championships in Berlin, in seconds?",
    label: "Usain Bolt's 2009 100 m world record",
    answer: 9.58,
    unit: "s",
    kind: "number",
    scale: "log",
    cat: "Sports",
    note: "An average speed of about 37.6 km/h.",
  },
  {
    id: "snooker-maximum-break",
    q: "What is the maximum break in snooker, without free balls?",
    label: "the maximum snooker break",
    answer: 147,
    unit: "points",
    kind: "number",
    scale: "log",
    cat: "Sports",
    note: "All 15 reds, each followed by the black, then all six colours.",
  },
  {
    id: "bowling-perfect-score",
    q: "What is a perfect score in ten-pin bowling?",
    label: "a perfect ten-pin bowling score",
    answer: 300,
    unit: "points",
    kind: "number",
    scale: "log",
    cat: "Sports",
    note: "Twelve strikes in a row.",
  },
  {
    id: "darts-max-three-dart-score",
    q: "What is the highest score possible with three darts?",
    label: "the maximum three-dart score",
    answer: 180,
    unit: "points",
    kind: "number",
    scale: "log",
    cat: "Sports",
    note: "Three treble 20s.",
  },
  // Tech
  {
    id: "intel-4004-transistors",
    q: "How many transistors did the Intel 4004, the first commercial microprocessor (1971), contain?",
    label: "the transistor count of the Intel 4004",
    answer: 2300,
    unit: "transistors",
    kind: "number",
    scale: "log",
    cat: "Tech",
    note: "The largest chips today contain more than 100 billion.",
  },
  {
    id: "ipv4-address-count",
    q: "How many possible IPv4 addresses are there, in billions?",
    label: "the number of possible IPv4 addresses",
    answer: 4.29,
    unit: "billion",
    kind: "number",
    scale: "log",
    cat: "Tech",
    note: "2³² = 4,294,967,296.",
  },
  {
    id: "channel-tunnel-length",
    q: "How long is the Channel Tunnel between England and France, in km?",
    label: "the length of the Channel Tunnel",
    answer: 50.5,
    unit: "km",
    kind: "number",
    scale: "log",
    cat: "Tech",
    note: "About 38 km of it runs under the sea.",
  },
  {
    id: "hoover-dam-height",
    q: "How tall is the Hoover Dam, in metres?",
    label: "the height of the Hoover Dam",
    answer: 221,
    unit: "m",
    kind: "number",
    scale: "log",
    cat: "Tech",
    note: "726 feet; it opened in 1936 on the Colorado River.",
  },
  {
    id: "floppy-disk-capacity",
    q: "What was the capacity of a standard 3.5-inch high-density floppy disk, in MB?",
    label: "the capacity of a 3.5-inch floppy disk",
    answer: 1.44,
    unit: "MB",
    kind: "number",
    scale: "log",
    cat: "Tech",
    note: "The '1.44 MB' was actually 1,474,560 bytes (1,440 × 1,024).",
  },
  {
    id: "eniac-weight",
    q: "Roughly how much did the ENIAC computer weigh, in tonnes?",
    label: "the weight of ENIAC",
    answer: 27,
    unit: "tonnes",
    kind: "number",
    scale: "log",
    cat: "Tech",
    note: "More than 30 US (short) tons.",
  },
];
